version: "3.7"

# Database + Webserver (under http, for testing setup on localhost:80)
#
# docker-compose -f docker-compose.dev.yml up -d
#

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
  frontend:
    depends_on:
      - backend
    restart: "unless-stopped"
    image: lurkingryuu/denormies_frontend:v1.0.3
    ports:
      - '7069:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
  backend:
    depends_on:
      - postgres
    restart: "unless-stopped"
    image: lurkingryuu/denormies_backend:v1.0.3
    env_file:
      - ./backend/.env
    environment:
      - DEFAULT_DATABASE_HOSTNAME=postgres
      - DEFAULT_DATABASE_PORT=5432
    ports:
      - '7420:8000'
volumes:
  postgres_data:
