"""schema update 1

Revision ID: a79df019647f
Revises: 07c71f4389b6
Create Date: 2024-02-29 19:00:59.910283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a79df019647f"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accomodation",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accomodation_name"), "accomodation", ["name"], unique=True)
    op.create_table(
        "mess",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mess_name"), "mess", ["name"], unique=True)
    op.create_table(
        "sponsor",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("desc", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sponsor_name"), "sponsor", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_phone"), "user", ["phone"], unique=True)
    op.create_table(
        "venue",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("desc", sa.String(length=100), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("venue", sa.String(length=20), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue"],
            ["venue.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_name"), "event", ["name"], unique=True)
    op.create_table(
        "organizer",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("responsibility", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participant",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("university", sa.String(length=100), nullable=False),
        sa.Column("accomodation", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("mess", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["accomodation"],
            ["accomodation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mess"],
            ["mess.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("roll", sa.String(length=20), nullable=False),
        sa.Column("dept", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_student_roll"), "student", ["roll"], unique=True)
    op.create_table(
        "competition",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("props", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manage",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "event_id"),
    )
    op.create_table(
        "prize",
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "position"),
    )
    op.create_table(
        "registration",
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("reg_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "user_id"),
    )
    op.create_table(
        "sponsorship",
        sa.Column("sponsor_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["sponsor.id"],
        ),
        sa.PrimaryKeyConstraint("sponsor_id", "event_id"),
    )
    op.create_table(
        "volunteer",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "event_id"),
    )
    op.drop_index("ix_user_model_email", table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=254), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_model_pkey"),
    )
    op.create_index("ix_user_model_email", "user_model", ["email"], unique=False)
    op.drop_table("volunteer")
    op.drop_table("sponsorship")
    op.drop_table("registration")
    op.drop_table("prize")
    op.drop_table("manage")
    op.drop_table("competition")
    op.drop_index(op.f("ix_student_roll"), table_name="student")
    op.drop_table("student")
    op.drop_table("participant")
    op.drop_table("organizer")
    op.drop_index(op.f("ix_event_name"), table_name="event")
    op.drop_table("event")
    op.drop_table("venue")
    op.drop_index(op.f("ix_user_phone"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_sponsor_name"), table_name="sponsor")
    op.drop_table("sponsor")
    op.drop_index(op.f("ix_mess_name"), table_name="mess")
    op.drop_table("mess")
    op.drop_index(op.f("ix_accomodation_name"), table_name="accomodation")
    op.drop_table("accomodation")
    # ### end Alembic commands ###
