"""DB Sizes changed

Revision ID: 1be94e8acb6e
Revises: d7de73343b4a
Create Date: 2024-03-04 14:16:52.317240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1be94e8acb6e"
down_revision = "d7de73343b4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
