"""Participant mess and acc id

Revision ID: ad8884ef3f1c
Revises: ee97f3e67f04
Create Date: 2024-03-02 15:53:41.254493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad8884ef3f1c"
down_revision = "ee97f3e67f04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("accomodation_id", sa.UUID(as_uuid=False), nullable=False),
    )
    op.add_column(
        "participant", sa.Column("mess_id", sa.UUID(as_uuid=False), nullable=False)
    )
    op.drop_constraint("participant_mess_fkey", "participant", type_="foreignkey")
    op.drop_constraint(
        "participant_accomodation_fkey", "participant", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "participant",
        "mess",
        ["mess_id"],
        ["id"],
        onupdate="SET NULL",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "participant",
        "accomodation",
        ["accomodation_id"],
        ["id"],
        onupdate="SET NULL",
        ondelete="SET NULL",
    )
    op.drop_column("participant", "mess")
    op.drop_column("participant", "accomodation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("accomodation", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "participant", sa.Column("mess", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.create_foreign_key(
        "participant_accomodation_fkey",
        "participant",
        "accomodation",
        ["accomodation"],
        ["id"],
        onupdate="SET NULL",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "participant_mess_fkey",
        "participant",
        "mess",
        ["mess"],
        ["id"],
        onupdate="SET NULL",
        ondelete="SET NULL",
    )
    op.drop_column("participant", "mess_id")
    op.drop_column("participant", "accomodation_id")
    # ### end Alembic commands ###
