"""Foreign Key is by default not null

Revision ID: 69cd98cf4a05
Revises: fc2ae955b528
Create Date: 2024-03-02 16:53:20.602402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69cd98cf4a05"
down_revision = "fc2ae955b528"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prize", "winner_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prize", "winner_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
