"""DB Unchanged

Revision ID: d7de73343b4a
Revises: 57f734605cd7
Create Date: 2024-03-02 20:02:19.315918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7de73343b4a"
down_revision = "57f734605cd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
