"""change data size of department

Revision ID: 3f23d8aca832
Revises: 459c35c3a19a
Create Date: 2024-03-02 16:31:11.548160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f23d8aca832"
down_revision = "459c35c3a19a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accomodation",
        "name",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "name",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "type",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "venue",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "manage",
        "position",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "mess",
        "name",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "sponsor",
        "name",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "student",
        "roll",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "student",
        "dept",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=120),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "phone",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "venue",
        "name",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "venue",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "role",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "phone",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=True,
    )
    op.alter_column(
        "student",
        "dept",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "student",
        "roll",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "sponsor",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "mess",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "manage",
        "position",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "venue",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "type",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "event",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "accomodation",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
