"""organizer schema removed

Revision ID: 2f0d39aa00c2
Revises: cc504b091ad3
Create Date: 2024-03-02 00:15:21.830424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f0d39aa00c2"
down_revision = "cc504b091ad3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organizer")
    op.add_column("manage", sa.Column("position", sa.String(length=20), nullable=False))
    op.add_column(
        "manage", sa.Column("responsibility", sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manage", "responsibility")
    op.drop_column("manage", "position")
    op.create_table(
        "organizer",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "position", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "responsibility",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["user.id"], name="organizer_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="organizer_pkey"),
    )
    # ### end Alembic commands ###
